#!/bin/bash
#
# Update the server's Tauri release config with the latest build info
# Usage: ./update-release-config.sh [--notes "Release notes"]
#
# This script updates server/src/config/tauri-release.ts with:
#   - Version from tauri.conf.json
#   - Signature from the build output (.sig file)
#   - Current date as pub_date
#
# Run this after uploading artifacts to R2.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TAURI_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$TAURI_DIR/.." && pwd)"
CONFIG_FILE="$REPO_DIR/server/src/config/tauri-release.ts"
BUNDLE_DIR="$TAURI_DIR/src-tauri/target/release/bundle/macos"

# Parse arguments
RELEASE_NOTES=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --notes)
            RELEASE_NOTES="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [--notes \"Release notes\"]"
            echo ""
            echo "Update the server's Tauri release config with the latest build info."
            echo ""
            echo "Options:"
            echo "  --notes    Release notes for this version"
            echo ""
            echo "This script reads from:"
            echo "  - tauri/src-tauri/tauri.conf.json (version)"
            echo "  - tauri/src-tauri/target/release/bundle/macos/*.sig (signature)"
            echo ""
            echo "And updates:"
            echo "  - server/src/config/tauri-release.ts"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Get version from tauri.conf.json
VERSION=$(grep '"version"' "$TAURI_DIR/src-tauri/tauri.conf.json" | head -1 | sed 's/.*: *"\([^"]*\)".*/\1/')

# Determine architecture
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
    ARCH_SUFFIX="aarch64"
    SIG_KEY="darwin-aarch64"
else
    ARCH_SUFFIX="x86_64"
    SIG_KEY="darwin-x86_64"
fi

# Find signature file
SIG_FILE="$BUNDLE_DIR/Clutch.app.tar.gz.sig"

if [ ! -f "$SIG_FILE" ]; then
    echo "Error: Signature file not found at $SIG_FILE"
    echo "Run './scripts/build-dmg.sh app' first to create the artifacts."
    exit 1
fi

# Read signature
SIGNATURE=$(cat "$SIG_FILE")

# Current date in ISO format
PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Default release notes
if [ -z "$RELEASE_NOTES" ]; then
    RELEASE_NOTES="Clutch v${VERSION}"
fi

echo "========================================"
echo "  Update Release Config"
echo "========================================"
echo ""
echo "Version: $VERSION"
echo "Architecture: $ARCH_SUFFIX"
echo "Pub Date: $PUB_DATE"
echo "Notes: $RELEASE_NOTES"
echo ""
echo "Signature ($SIG_KEY):"
echo "  ${SIGNATURE:0:50}..."
echo ""

# Read existing config to preserve other platform signatures
EXISTING_DARWIN_AARCH64=""
EXISTING_DARWIN_X86_64=""
EXISTING_LINUX_X86_64=""
EXISTING_WINDOWS_X86_64=""

if [ -f "$CONFIG_FILE" ]; then
    EXISTING_DARWIN_AARCH64=$(grep '"darwin-aarch64":' "$CONFIG_FILE" | sed 's/.*: *"\([^"]*\)".*/\1/' || echo "")
    EXISTING_DARWIN_X86_64=$(grep '"darwin-x86_64":' "$CONFIG_FILE" | sed 's/.*: *"\([^"]*\)".*/\1/' || echo "")
    EXISTING_LINUX_X86_64=$(grep '"linux-x86_64":' "$CONFIG_FILE" | sed 's/.*: *"\([^"]*\)".*/\1/' || echo "")
    EXISTING_WINDOWS_X86_64=$(grep '"windows-x86_64":' "$CONFIG_FILE" | sed 's/.*: *"\([^"]*\)".*/\1/' || echo "")
fi

# Update the signature for current platform
if [ "$SIG_KEY" = "darwin-aarch64" ]; then
    EXISTING_DARWIN_AARCH64="$SIGNATURE"
else
    EXISTING_DARWIN_X86_64="$SIGNATURE"
fi

# Write the config file
cat > "$CONFIG_FILE" << EOF
/**
 * Tauri release configuration
 *
 * This file is auto-generated by tauri/scripts/update-release-config.sh
 * Do not edit manually - run the script after uploading a new release to R2
 */

export const tauriRelease = {
	version: "${VERSION}",
	notes: "${RELEASE_NOTES}",
	pubDate: "${PUB_DATE}",

	/** Base URL for R2 bucket where releases are hosted */
	r2BucketUrl: "https://pub-349c2b6f52cb45f6b00d16404e327b0d.r2.dev/tauri",

	/** Signatures for each platform (from .sig files) */
	signatures: {
		"darwin-aarch64": "${EXISTING_DARWIN_AARCH64}",
		"darwin-x86_64": "${EXISTING_DARWIN_X86_64}",
		"linux-x86_64": "${EXISTING_LINUX_X86_64}",
		"windows-x86_64": "${EXISTING_WINDOWS_X86_64}",
	},
} as const;
EOF

echo "Updated: $CONFIG_FILE"
echo ""
echo "========================================"
echo "  Next Steps"
echo "========================================"
echo ""
echo "1. Commit the updated config:"
echo "   git add server/src/config/tauri-release.ts"
echo "   git commit -m \"release: tauri v${VERSION}\""
echo ""
echo "2. Deploy the server to apply the update"
echo ""
echo "3. Test the updater endpoint:"
echo "   curl https://api.clutch.computer/api/updater/latest | jq"
echo ""
